My personal system configuration.

* Repository rules

- Scripts in =scripts/= must be written in Guile.
- Shell scripts are not allowed in this repo, even for trivial launchers or wrappers.

* QA

- Run =make qa= for the fast repository policy check.
- Run =make qa-home-samuel= before changing Samuel's home configuration.
- Run =make qa-home-levi= before changing Levi's home configuration.
- Run =make qa-system-x1= or =make qa-system-t450s= when changing system definitions.
- See =QA.md= for the broader cleanup roadmap.

* Installation

1. Install Guix System. 
2. Clone this repo as "$HOME/Projects/System/".
3. Create an adapted version of the system files in /systems. Especially make sure to update the uuids for your partition.
4. "Update" channels, system and home:   
   
** Update channels
#+begin_src sh
guix pull --channels=$HOME/Projects/System/channels.scm
#+end_src

** Update system
#+begin_src sh
sudo guix system --load-path=$HOME/Projects/System/systems reconfigure $HOME/Projects/System/systems/$HOSTNAME.scm
#+end_src

** Update home

#+begin_src sh
guix home --load-path=$HOME/Projects/System/home reconfigure $HOME/Projects/System/home/$USER-home-configuration.scm
#+end_src
