(define-module (samuel-home-configuration)
  #:use-module (gnu home)
  #:use-module (gnu home services)
  #:use-module (gnu home services shells)
  #:use-module (base-home)
  #:use-module (services fish)
  #:use-module (services starship)
  #:use-module (services konsole)
  #:use-module (services helix)
  #:use-module (services lem)
  #:use-module (services agent-skills)
  #:use-module (services agent-launchers)
  #:use-module (services claude))

(home-environment
 (packages
  (cons ((@ (packages base-packages) for-emacs-next)
         (@ (packages valsi) emacs-valsi))
        ((@ (packages base-packages) all-packages))))
 (services
  (append (base-services)
          (list (fish-service)
                (starship-service)
                (helix-service)
                (lem-service)
                (agent-skills-service)
                (claude-service))
          (konsole-services)
          (agent-launcher-services))))
