(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-overwrite-define-key
   '("n" . meow-next)
   '("p" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; SPC j/k will run the original command in MOTION state.
   ;; '("j" . "H-j")
   ;; '("k" . "H-k")
   ;; ;; Use SPC (0-9) for digit arguments.
   ;; ;'("1" . meow-digit-argument)
   ;; ;'("2" . meow-digit-argument)
   ;; '("3" . meow-digit-argument)
   ;; '("4" . meow-digit-argument)
   ;; '("5" . meow-digit-argument)
   ;; '("6" . meow-digit-argument)   ;; '("7" . meow-digit-argument)
   ;; '("8" . meow-digit-argument)
   ;; '("9" . meow-digit-argument)
   ;; '("0" . meow-digit-argument)
   ;'("/" . meow-keypad-describe-key)
   ;'("?" . meow-cheatsheet)
   ; NO x, h, g, m or c (already defined as C-x ...
   '("p" . sls-new-entry-pkb)
   '("E" . sls-export-org-to-html-and-pdf)
   '("e" . eat)
   '("v" . magit-status)
   '("d" . dired)
   '("b" . ibuffer)
   '("s" . imenu-list-smart-toggle)
   '("y" . sls-copy-file-path)
   '("m" . consult-bookmark)
   )
  (meow-normal-define-key
   '("ü" . delete-window)
   '("ö" . other-window)
   '("ä" . make-frame-command)
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . avy-goto-char-2)
   ;;'("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)

   '("c" . copy-region-as-kill)
   ;'("C" . meow-save )
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . sudo-edit-find-file)
   '("F" . meow-find)
   ;; F
   '("G" . meow-cancel-selection)
   '("g" . meow-grab)
   ;; h
   ;; H
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-prev)
   '("J" . meow-prev-expand)
   '("k" . meow-next)
   '("K" . meow-next-expand)
   '("r" . meow-right)
   '("l" . meow-left)
   '("L" . meow-left-expand)

   '("R" . meow-right-expand)
   '("m" . execute-command)
   ;'("m" . meow-join)
   ;'("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("" . meow-replace)
   '("" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("ß" . comment-or-uncomment-region)
   '("'" . repeat)
   ;'("TAB" . hs-hide-block)
   '("<escape>" . ignore)
   '("." . meow-cancel-selection)))

(require 'meow)
(meow-setup)
(meow-global-mode 1)


(provide 'keybindings-config)
