(provide 'navigation-config)

(setq display-buffer-alist
      `((,(rx bos "*Help*" eos)
         (display-buffer-in-direction)
         (direction . right)
         (window-width . 0.33))
        (,(rx bos "*compilation*" eos)
         (display-buffer-in-direction)
         (direction . bottom)
         (window-height . 0.33))
        (,(rx bos "*shell*" eos)
         (display-buffer-in-direction)
         (direction . top)
         (window-height . 0.33))
        (,(rx bos (or "*dired" "*Dired")) eos)
         (display-buffer-in-direction)
         (direction . left)
         (window-width . 0.33))))
