;;; keybindings-config.el --- Meow modal keybindings -*- lexical-binding: t -*-
;;; Code:

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-overwrite-define-key
   '("n" . meow-next)
   '("p" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; Navigation panels (all open in right side window)
   '("d" . dired)
   '("D" . sls-dired-sidebar-toggle)
   '("i" . ibuffer)
   '("s" . imenu-list-smart-toggle)
   '("r" . sls-recentf-open)
   '("b" . bookmark-bmenu-list)
   ;; Actions
   '("p" . sls-new-entry-pkb)
   '("E" . sls-export-org-to-html-and-pdf)
   '("t" . eat)
   '("v" . magit-status)
   '("y" . sls-copy-file-path)
   '("f" . delete-other-windows))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . avy-goto-char-2)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . copy-region-as-kill)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . sudo-edit-find-file)
   '("F" . meow-find)
   '("G" . meow-cancel-selection)
   '("g" . meow-grab)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-prev)
   '("J" . meow-prev-expand)
   '("k" . meow-next)
   '("K" . meow-next-expand)
   '("l" . meow-left)
   '("L" . meow-left-expand)
   '("r" . meow-right)
   '("R" . meow-right-expand)
   '("m" . execute-extended-command)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("ß" . comment-or-uncomment-region)
   '("'" . repeat)
   '("<escape>" . ignore)))

(require 'meow)
(meow-setup)
(meow-global-mode 1)

(provide 'keybindings-config)
;;; keybindings-config.el ends here
