(define-module (my packages font )
  #:use-module (ice-9 regex)
  #:use-module (guix utils)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix build-system font)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system meson)
  #:use-module (guix build-system trivial)
  #:use-module (gnu packages c)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages gd)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages sdl)
  #:use-module (gnu packages xorg))

(define-public font-inter
  (package
    (name "font-inter")
    (version "4.0-beta9h")
    (source (origin
              (method url-fetch)
              (uri (string-append "https://github.com/rsms/inter/releases/download/v" version "/Inter-" version ".zip"))
              (sha256 (base32 "16nawzmbm1h6jrn3nhsgsm3iks4d0f81rfv38dywjfnnxj1hmvgs"))))
    (build-system font-build-system)
    (home-page "https://rsms.me/inter/")
    (synopsis "The Inter font")
    (description "Inter is a typeface carefully crafted & designed for computer screens.")
    (license license:silofl1.1)))


font-inter
